recvStartLine 구현 및 클래스 리네이밍
404-DriverNotFound/418-imateapot pull request #10
Opened 2021-04-15 05:10 UTC by hyo-choi

이전 커밋과 병합이 되지 않은 상태라 테스트되지 않은 상태로 커밋합니다.

### 변경점
- recvStartLine 구현 (함수 내부에 건의사항 있음)
- StartLine 구조체, Http 클래스 구조 변경
- 각종 private 변수명 수정 (name -> _name)
- Url, Path 클래스 및 파일 삭제
- 그 외 구현상 필요한 함수 추가

2021-04-15 13:13 UTC, cos18 requested changes
이후 맥 환경에서 컴파일 & 테스트 가능한 Github Actions를 만들어봐야겠군요 환경에 따라 컴파일 결과가 다른 것 같습니다 ㅠㅠ

2021-04-15 13:13 UTC, cos18 commented on srcs/webserv.cpp
> +	}
이런 테스트를 돌릴 수 있는 코드를 `webserv.cpp`가 아니라 `test/test_startline.cpp`와 같이 따로 빼는 방법도 생각해봐야될것 같아요. 이건 내일(4/16)에 이야기해보면 좋을 것 같습니다!

2021-04-15 13:13 UTC, cos18 commented on srcs/Method.cpp
> +		return -1;
이건 개인 취향이긴 한데 에러 값을 따로 #define을 해서 처리를 하면 좀 더 코드 가독성이 좋아질 것 같아요!

2021-04-15 13:13 UTC, cos18 commented on srcs/Client.cpp
> +	 */
저도 동의합니다! 이 부분도 금요일에 이야기해보죠

2021-04-15 13:13 UTC, cos18 commented on srcs/webserv.cpp
> +	Client a;
Mac에서 컴파일이 되지 않습니다.

private 맴버에 참조변수가 있어 생성자 과정에서 값을 할당해야된다는것과,
private 맴버인 _request를 가져올 수 없다는 에러가 뜹니다.

자세한 에러 로그는 다음과 같습니다.
```
./includes/Client.hpp:23:7: error: implicit default constructor for 'Client'
      must explicitly initialize the reference member '_config_location'
class Client
      ^
srcs/webserv.cpp:18:9: note: in implicit default constructor for 'Client' first
      required here
        Client a;
               ^
./includes/Client.hpp:31:13: note: declared here
                Config                  &_config_location;
                                         ^
srcs/webserv.cpp:30:24: error: '_request' is a private member of 'Client'
                        StartLineReq &b = a._request.getStartLine();
                                            ^
./includes/Client.hpp:29:16: note: declared private here
                HttpRequest             _request;
                                        ^
```

2021-04-15 13:15 UTC, aymin91 commented on srcs/webserv.cpp
> +	Client a;
저도 이거 떴었는데 잠시 private을 public으로 바꿔서 값이 제대로 들어가는지만 확인하는 정도로만 했었습니다.

2021-04-15 13:16 UTC, aymin91 commented on srcs/webserv.cpp
> +	}
넵 이것도 아까 헷갈린다고 이야기했었습니다 ㅠ
내일 테스트 관련한 파일 또는 폴더를 만들어 보아요

2021-04-15 15:12 UTC, hyo-choi commented on srcs/webserv.cpp
> +	}
넵! 일단은 지우지 않고 둘게요~

2021-04-15 15:18 UTC, hyo-choi commented on srcs/webserv.cpp
> +	Client a;
이 부분은 컴파일이 안 되는 게 맞습니다!
제가 설명을 안 적어뒀네요. ㅠㅠ

동작 확인용으로 잠시 생성자를 만들었었고, amin님 말씀처럼 private 멤버를 public으로 옮겨서 테스트 한 뒤에 임시로 바꾼 부분을 원래대로 돌려놨었습니다.
[위의 코멘트](https://github.com/404-DriverNotFound/418-imateapot/pull/10#discussion_r614048399)에서 말씀하신 것처럼 테스트용 파일을 따로 만드는 게 좋을 것 같기도 하고, 컴파일 관련하여 혼동의 여지가 있으니 이 파일은 그냥 커밋에서 제외하겠습니다!

2021-04-15 15:19 UTC, hyo-choi commented on srcs/webserv.cpp
> +	}
넵! 그러면 [아래 이슈](https://github.com/404-DriverNotFound/418-imateapot/pull/10#discussion_r614055753)도 있고 하니 이 파일은 커밋에서 제외하겠습니다!

2021-04-15 15:20 UTC, hyo-choi commented on srcs/Method.cpp
> +		return -1;
확실히 그렇게 하는 편이 더 좋을 것 같네요! webserv.cpp 삭제하는 김에 이 부분도 반영할게요~

2021-04-16 05:32 UTC, cos18 approved these changes
LGTM

2021-04-16 05:32 UTC, aymin91 approved these changes
룩굳투미

2021-04-16 05:32 UTC, merged