Feature/#19
404-DriverNotFound/418-imateapot pull request #21
Opened 2021-04-23 11:13 UTC by aymin91

- 401, 403, 405 에러 처리

2021-04-23 11:34 UTC, cos18 requested changes
수고 많이 하셨습니다! 사소한 내용 한가지만 수정해주시면 될것같아요!

2021-04-23 11:34 UTC, cos18 commented on srcs/Client.cpp
> +	}
![](https://mdn.mozillademos.org/files/14689/HTTPAuth.png)
다음과 같이 `Authorization: Basic auth_key` 이런 방식으로 들어와서
저희 config에 `auth auth_key`로 설정되어있을때 통과되는식으로 처리해주시면 될것 같아요!

2021-04-24 05:51 UTC, aymin91 commented
허허.. 인터넷이 이상해서 안 올라간 줄 알아서 2번이나 올리게 되었네요 죄송합니다!

2021-04-24 12:50 UTC, cos18 requested changes
추가적으로, 변경사항 요청한 내용을 모두 수정하실때 review를 re-request해주세요!

[참고](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)

2021-04-24 12:50 UTC, cos18 commented on srcs/Client.cpp
> +	}
```suggestion
	if (!this->_config_location->auth.empty())
	{
		std::string auth_value = this->_request.getHeaderValue("Authorization");
		if (auth_value.empty())
			throw 401;
		std::vector<std::string> temp = ft_split(auth_value, ' ');
		if (temp.length != 2 || temp[0].compare("Basic") || temp[1].compare(this->_config_location->auth))
			throw 403;
	}
```

- Request Header에 Authorization이 없는 경우
- Authorization 방식이 Basic이 아닌경우
- string compare 함수 실행시 ! 제거

등 문제가 있을 거 같아 위와 같이 구현해야 될 것 같습니다

2021-04-25 07:26 UTC, hyo-choi commented on srcs/Client.cpp
> +	}
저도 한 번 다시 훑어봤고 이 부분만 수정해주시면 될 것 같아요~ 👌

2021-04-25 10:03 UTC, cos18 commented
@aymin91 main 브랜치 머지해주세요!

2021-04-25 10:47 UTC, merged