간단한 Body reciever 추가 & HTTP body 구조 변경
404-DriverNotFound/418-imateapot pull request #22
Opened 2021-04-23 11:18 UTC by cos18

**현재 작업 진행중이라 코드만 보시고 문제 있으면 알려주세요!! 작업 완료시 리뷰 할당해드리겠습니다!!**

recvBody 함수를 구현하고, 특히 chunked 인코딩 방식으로 진행될 경우 이를 해결해주는 로직을 추가했습니다.

추가로 body 변수 타입을 변경했습니다. 이에 대해선 말로 설명해드렸습니다!

2021-04-23 11:27 UTC, cos18 commented
현재 추가로 구현해야 되는 내용

- [ ] `atoi`, `strtol`이 forbidden 함수라 이를 구현해야 함
- [ ] Content-Length에 맞게 데이터를 들어온 이후 클라이언트 종료
- [ ] Chunked 가 종료될때 (0\r\n\r\n) 클라이언트 종료 처리
- [ ] 데이터가 끝나는 파트에서 클라이언트 종료 처리

2021-04-24 15:34 UTC, cos18 commented
위 구현 내용중 마지막 "데이터 끝나는 파트에서 클라 종료"의 경우 전송까지 마무리된 이후 정리하는 식으로 구현해야 될 것 같습니다!

2021-04-25 07:23 UTC, hyo-choi requested changes
전반적인 로직은 잘 짜주셔서 문제 없는 것 같고, 자잘한 수정사항 발견해서 리뷰 남깁니다!
주말인데도 고생 많으셨어요~ (_ _

2021-04-25 07:23 UTC, hyo-choi commented on srcs/utils.cpp
> +			minus_flag = -1;
이 부분 순서가 바뀐 것 같습니다!
```suggestion
		if (str[index] == '-')
			minus_flag = -1;
		index++;
```

2021-04-25 07:23 UTC, hyo-choi commented on srcs/utils.cpp
> +	unsigned long long result = 0;
아래에서 result에 -1을 곱하게 될 수도 있으니 unsigned long long을 쓰면 안 될 것 같아요.
```suggestion
	long long result = 0;
```

2021-04-25 07:23 UTC, hyo-choi commented on srcs/Client.cpp
> +		if (tmp.length() < this->_content_length_left)
이 부분의 역할이 `현재 가지고 있는 line(tmp)의 길이`가 `Content-Length의 남은 길이`보다 길다면 초과분을 지워주는 게 맞을까요?
그러면 꺽쇠 방향을 고쳐줘야 할 것 같습니다. 혹시 제가 잘못 이해했다면 코멘트 부탁드려요!
```suggestion
		if (tmp.length() > this->_content_length_left)
```

2021-04-25 07:27 UTC, cos18 commented on srcs/Client.cpp
> +		if (tmp.length() < this->_content_length_left)
맞습니다 ㅠㅜ 제가 햇갈리고 막 코드를 갈겨놨군요 ㅠㅜ

2021-04-25 11:13 UTC, hyo-choi approved these changes
LGTM!

2021-04-25 14:17 UTC, aymin91 approved these changes
고생하셨습니다.

2021-04-25 14:19 UTC, merged