put method 구현
404-DriverNotFound/418-imateapot pull request #29
Opened 2021-04-26 09:17 UTC by aymin91

- [ ] makePutMsg() 구현
- [ ] 이하 상황별 _response.getStartLine().status_code 변경
       ㄴ 파일이 있는 경우 : 204
       ㄴ 파일이 없는 경우 : 201
       ㄴ 그 외 에러인 경우 : 403
- [ ] isFilePath() 구현(utils.cpp)
- [ ] isDirPath() 구현(utils.cpp)

2021-04-26 09:26 UTC, hyo-choi submitted a review, later dismissed
LGTM!!

2021-04-26 13:35 UTC, cos18 requested changes

2021-04-26 13:35 UTC, cos18 commented on srcs/Client.cpp
> +		file << content[i] << "\r\n";
이런식으로 처리하게 되면 100만바이트 짜리 데이터가 들어왔을때 deque에서 한번에 처리할 수 없습니다. (= makePutMsg 함수가 호출될때 모든 바디 데이터가 read되었다고 보장할 수 없습니다.)

처리를 무한번 반복하면서 바디가 모두 read될때 반복문을 탈출하는 식으로 구현을 바꿔야합니다. 이건 화요일에 오프라인에서 이야기해보죠!

2021-04-29 05:49 UTC, hyo-choi approved these changes
LGTM!

2021-04-29 05:49 UTC, cos18 approved these changes
LGTM

2021-04-29 05:50 UTC, merged