body_length에 따른 status  변경 및 head_length 삭제
404-DriverNotFound/418-imateapot pull request #30
Opened 2021-04-26 09:29 UTC by hyo-choi

close #26 

- 서버 config 파일에 명시된 body_length로 body의 길이를 제한하였습니다.
- head_length를 사용하지 않기로 하였으므로 해당 변수와 관련된 내용을 삭제하였습니다.

2021-04-26 09:35 UTC, aymin91 approved these changes, later dismissed
룩굿투미

2021-04-26 13:29 UTC, cos18 requested changes

2021-04-26 13:29 UTC, cos18 commented on srcs/Client.cpp
> +			this->_body_length_left -= (pos + 1);
body_length_left가 pos (tmp 길이)보다 작을 경우 body_length_left만큼의 문자만 body deque에 저장해야 합니다.
현재 이를 처리하시지 않은 것 같습니다 ㅠㅠ

2021-04-26 17:53 UTC, hyo-choi commented on srcs/Client.cpp
> +			this->_body_length_left -= (pos + 1);
확인했습니다! 👍 다시 읽어보니 chunked에서도 해당 처리가 이루어지지 않은 것 같아 오늘 낮에 수정하겠습니다~

2021-04-27 05:52 UTC, cos18 approved these changes
LGTM!

2021-04-27 05:58 UTC, aymin91 approved these changes
룩꿌뚜미

2021-04-27 05:58 UTC, merged