solve #1
404-DriverNotFound/418-imateapot pull request #7
Opened 2021-04-14 12:14 UTC by aymin91

closed #1

2021-04-14 12:52 UTC, hyo-choi requested changes
- checkDup 함수 2가지에서 공통적으로 문제가 될 만한 부분을 발견해 수정 요청 드립니다.
  확인 부탁드려요~

2021-04-14 12:52 UTC, hyo-choi commented on srcs/ConfigGroup.cpp
> +	for (; it < ite ; it++)
- 중복 검사가 인접한 요소들 사이에서만 이루어지는 것 같습니다.
  [0, 1], [1, 2] , [2, 3], [3, 4], ... 끼리만 중복 여부를 검사하고 [0, 2], [0, 3], ... 등은 검사되지 않는 것 같아요.
  수정 부탁드립니다!

2021-04-14 12:52 UTC, hyo-choi commented on srcs/ConfigGroup.cpp
> +	for (int i = 0; i < getServerCnt() - 1; i++)
- checkDupLocation과 같은 이슈가 있습니다. 확인 부탁드려요!

2021-04-14 14:55 UTC, cos18 reviewed
추가로 PR 제목도 의미있게 적어주시면 감사드리겠습니다!

일단 효정님이 언급하신 내용만 수정하시면 문제 없을 것 같습니다!

2021-04-14 14:55 UTC, cos18 commented on includes/Http.hpp
> +
요런 불필요한 파일 수정은 커밋을 자제해주시는게 이후 머지 과정에서 충돌날 확률이 줄어듭니다!

2021-04-14 15:08 UTC, cos18 commented
@aymin91 PR을 closed하는 이유가 무엇인가요?

2021-04-14 15:16 UTC, aymin91 commented on includes/Http.hpp
> +
죄송합니다! ㅠㅠ 이래저래 파일 보다가 불필요한 줄을 지우는 정도만 했는데 그게 반영된 것 같습니다 ㅠ

2021-04-14 15:38 UTC, cos18 requested changes

2021-04-14 15:38 UTC, cos18 commented on srcs/ConfigGroup.cpp
> +	}
```suggestion
	for (int i = 0; i < size - 1; i++)
	{
		for (int j = i; j < size; j++)
		{
			if (server_vector[i].location_path == server_vector[j].location_path)
				return false;
		}
	}
```

요런식으로 수정하셔야 모든 블록들을 비교할 수 있을 것 같아요.

2021-04-14 15:38 UTC, cos18 commented on srcs/ConfigGroup.cpp
> +	}
위와 같이 재수정 부탁드립니다!

2021-04-14 23:46 UTC, aymin91 commented on srcs/ConfigGroup.cpp
> +	}
재수정해서 커밋했습니다.

2021-04-14 23:46 UTC, aymin91 commented on srcs/ConfigGroup.cpp
> +	}
재수정해서 커밋했습니다.

2021-04-15 02:47 UTC, hyo-choi approved these changes
- 문제 없는 것 같습니다. 고생하셨습니다!

2021-04-15 04:15 UTC, cos18 approved these changes
LGTM

2021-04-15 04:15 UTC, merged